Модуль 1, задачи 4-5
js-tasks-ru/jsbasic-20230428_lunokot9 pull request #3
Opened 2023-05-04 08:33 UTC by lunokot1

2023-05-04 08:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-04 09:13 UTC, SinimaWath requested changes

2023-05-04 09:13 UTC, SinimaWath commented on 1-module/4-task/index.js
> +    return (str.includes('xxx') || str.includes('1xbet') || false);
`return str.includes('xxx') || str.includes('1xbet')`, так как в любом случае includes вернет true или false

2023-05-04 11:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-05 10:11 UTC, SinimaWath approved these changes

2023-05-05 10:12 UTC, merged